### ISSUE TITLE
Add Support for zip_source_function

### ISSUE THREAD

**Issue by arsnyder16** [ctabin/libzippp#10]
Any plan to add support for zip_source_function?

wrapping zip_source_function will allow for better performance when writing/reading large zip entries. This will allow users to write to the zip dynamically without the need to read/write to a temp file or a contiguous block of memory

**Comment by ctabin** [comment]
Hello,

Sorry for the late reply. Your are totally right about zip_source_function and I'll see how I can possibly include id in libzippp.

**Comment by ctabin** [comment]
In the next version, a new function `ZipArchive::fromSource` has been added.
