### ISSUE TITLE
can't caculate file size which file has chinese filename on windows

### ISSUE THREAD

**Issue by bjrxyz** [ctabin/libzippp#104]
https://github.com/ctabin/libzippp/blob/8299422194ce3c5be0677550ce3d6d4e15d40dd8/src/libzippp.cpp#L548
libzip use utf-8 codec on windows, so all string argument should use  utf-8,but this code use ansi codec on windows

**Comment by ctabin** [comment]
Hi @bjrxyz,
Thanks for your report.
Do you have any suggestion on how it should be handled ?

**Comment by bjrxyz** [comment]
> Hi @bjrxyz,
> Thanks for your report.
> Do you have any suggestion on how it should be handled ?

I read the doc at [https://linux.die.net/man/3/zip_source_file](url)
if call zip_source_file with len=0 or len=-1,that mean use whole file.
so the code to caculate file size is not required
