### ISSUE TITLE
Implement zip_register_progress_callback_with_state function

### ISSUE THREAD

**Issue by billvog** [ctabin/libzippp#106]
Any plan implementing `zip_register_progress_callback_with_state`?

I think is important to wrap this function because dealing with big files while not having a form of progress bar is not a good experience for the end-user.

**Comment by ctabin** [comment]
Hi @billvog,
Thanks for the suggestion. It seems pretty easy to implement and I agree that it is really useful for the end user.
So, I'll definitely implement it asap.
