### ISSUE TITLE
ZipArchive::fromBuffer shouldn't return a pointer that should be deleted by the user

### ISSUE THREAD

**Issue by lanyizi** [ctabin/libzippp#117]
https://github.com/ctabin/libzippp/blob/e79fe8d0ab3f4d41ccd74a2773f8e6097aaa6eba/src/libzippp.h#L184

By returning a pointer created from `new` (and requiring users to use `delete` on it), it would be really easy to let users call `delete` across DLL boundaries, which might cause issues. 
There are plenty of questions about it on StackOverflow, for example: https://stackoverflow.com/questions/443147/c-mix-new-delete-between-libs

I suggest to provide a `static void ZipArchive::free(ZipArchive*)` function, which calls delete from libzippp's translation unit, and require users to call this function (instead of calling `delete` inside their own translation unit) for any `ZipArchive` pointers returned from this library (for example returned by `ZipArchive::fromBuffer`).
We could even provide a smart pointer:
```cpp
// inside libzippp.h
class ZipArchive;

struct ZipArchiveDeleter {
    void operator()(ZipArchive* p) const noexcept;
};
using ZipArchivePointer = std::unique_ptr<ZipArchive, ZipArchiveDeleter>;

class LIBZIPPP_API ZipArchive {
public:
    // implementation should be inside libzippp's translation unit
    static void ZipArchive::free(ZipArchive* p) noexcept;
    // old version, users should be advised to use ZipArchive::free() instead of operator delete
    static ZipArchive* fromBuffer(...);
    // new version, which is also safer because it uses smart pointer
    static ZipArchivePointer fromBuffer(...);
}

// inside libzippp.cpp
void ZipArchive::free(ZipArchive* p) noexcept {
    delete p;
}
void ZipArchiveDeleter::operator()(ZipArchive* p) const noexcept {
    ZipArchive::free(p);
}
```

**Comment by ctabin** [comment]
Hi @lanyizi,
Thanks for your report.
I'll take a deeper look at your suggestion, which makes sens to me.
However, since I'm no familiar with smart pointers, I need to do some deeper tests.

**Comment by ctabin** [comment]
The `ZipArchive::free` method has been added (#134) and documentation has been updated according to it. For now, I won't integrate a smart pointer.
