### ISSUE TITLE
Failed to link static lib in VS2015

### ISSUE THREAD

**Issue by sinall** [ctabin/libzippp#14]
Does the pre-compiled lib compatible with VS2015? I got link errors:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: bool __thiscall libzippp::ZipArchive::open(enum libzippp::ZipArchive::OpenMode,bool)" (__imp_?open@ZipArchive@libzippp@@QAE_NW4OpenMode@12@_N@Z) referenced in function "public: void __thiscall UnitTest::ZipTest::ShouldUnzip(void)" (?ShouldUnzip@ZipTest@UnitTest@@QAEXXZ)	UnitTest	C:\Users\xxx\Documents\Visual_Studio_2015\Projects\UnitTest\ZipTest.obj	1	
> Error	LNK1120	3 unresolved externals	UnitTest	C:\Users\ruigao\Documents\Visual_Studio_2015\Projects\ShiPanE\Debug\UnitTest.dll	1	
> Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: virtual __thiscall libzippp::ZipArchive::~ZipArchive(void)" (__imp_??1ZipArchive@libzippp@@UAE@XZ) referenced in function "public: void __thiscall UnitTest::ZipTest::ShouldUnzip(void)" (?ShouldUnzip@ZipTest@UnitTest@@QAEXXZ)	UnitTest	C:\Users\ruigao\Documents\Visual_Studio_2015\Projects\UnitTest\ZipTest.obj	1	
> Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: __thiscall libzippp::ZipArchive::ZipArchive(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (__imp_??0ZipArchive@libzippp@@QAE@ABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) referenced in function "public: void __thiscall UnitTest::ZipTest::ShouldUnzip(void)" (?ShouldUnzip@ZipTest@UnitTest@@QAEXXZ)	UnitTest	C:\Users\ruigao\Documents\Visual_Studio_2015\Projects\UnitTest\ZipTest.obj	1	
> 

Interesting thing is I could link successfully with (libzippp.lib), but unable to run the application.

**Comment by sinall** [comment]
Even if use the 'release' version libs, I got 'bad allocation' exception when constructing ZipArchive.

**Comment by sinall** [comment]
BTW, both libzip and libz are available on Nuget, so depending on those lib in VS2015 will be very easy.

**Comment by embeddedmz** [comment]
I have already tested libzippp under VS2015 and it works perfectly. Use CMake (gui) to configure/generate the dependencies builds.

**Comment by ctabin** [comment]
Hello,

Unfortunately, I didn't tested it on VS2015 and I don't have the resources to make it. Maybe could you submit a PR with a solution ?
