### ISSUE TITLE
How to extract non-English file name?

### ISSUE THREAD

**Issue by sinall** [ctabin/libzippp#15]
I failed to extract non-English file name, even if I replace zip_open with windows_open from libzip's example.
Environment: Win10 + VS2015 + zip archived by 7zip.
Do you know how to do that?

**Comment by ctabin** [comment]
Hello,
Can you provide an zip and the entry that causes problem ?

**Comment by sinall** [comment]
[archive.zip](https://github.com/ctabin/libzippp/files/870041/archive.zip)

Password: testpassword
The file name is '新建文本文档.txt'

**Comment by ctabin** [comment]
I'm not sure it is a libzip/libzippp issue, because if I use unzip -l on your archive, it doesn't print well.
Hence, I'm suspecting it is related to some encoding problem with 7z... It may be worth to try creating a new archive using libzip(pp) with the specified entry name.

**Comment by sinall** [comment]
I tested zip archived by GnuWin32 and it works now. Only thing left is to figure out how to pass password to the command line, that should be trivial I guess.
