### ISSUE TITLE
How To add an existing directory/file into my Zip Archive ?

### ISSUE THREAD

**Issue by beemibrahim** [ctabin/libzippp#154]

**Comment by flomnes** [comment]
AFAIK, there is no way to add a directory in one go. You may want to use [https://en.cppreference.com/w/cpp/filesystem/recursive_directory_iterator](`std::filesystem::recursive_directory_iterator`), available with most recent compilers (C++17 feature).

To add files, you may use `ZipArchive::addFile`. You may add a directory with `ZipArchive::addEntry`.

Combining the info above, you should be able to zip a file hierarchy quite easily.

**Comment by ctabin** [comment]
Hi @beemibrahim,

According to @flomnes, there is no direct way to add a directory in the `ZipArchive` because of cross-compatibility problems due to file/directory handling.
