### ISSUE TITLE
Issue including into VS project.

### ISSUE THREAD

**Issue by Stanlyhalo** [ctabin/libzippp#159]
Hey, so I ran the compile.bat file to compile to the dist folder. And than I had that copied to a better folder for my own management. I had the include additional directories point towards it and same goes with the additional library directories. I than also added the libzippp.lib to the additional dependencies. This is typically the process for all APIs I download. However, when I start it says that libzippp.dll was not found. And if I put that in the Release folder, than it says jvm.dll was not found.

**Comment by Stanlyhalo** [comment]
If I dig into my java bin folder and copy jvm.dll over to my project's output, I now get this error:
![image](https://user-images.githubusercontent.com/36088749/187057506-ca114366-26ab-4bd0-9ce5-65b262dcd28a.png)

**Comment by ctabin** [comment]
Hi @Stanlyhalo,
There is nothing special with the installation of libzippp :thinking: Maybe it's something related to your install ?
Would you be able to provide a simple reproducible testcase ? Thanks.

**Comment by ctabin** [comment]
Without response, I'm closing this issue. Feel free to open it if you're able to provide a testcase.
