### ISSUE TITLE
Setting the compression method doesn't works

### ISSUE THREAD

**Issue by Bob590** [ctabin/libzippp#162]
Hi,
I'm using the zip archiver in a special way. As I have a folder with many BIG files that are already compressed then I need to only package those files inside a single zip archive.
So I have tried to set the compression method to STORE in order to avoid to waste time compressing something that is already compressed.
Well, it doesn't work.

To excite the bug use a code similar to this one:

	libzippp::ZipArchive zf(C:\\Test\\test.zip);
	zf.open(libzippp::ZipArchive::Write);
	zf.setCompressionMethod(STORE);
	std::string lfilename = "myfile.bin";
	std::string lfilepath = "C:\\Test\\myfile.bin";
	zf.addFile(lfilename, lfinepath);
	zf.close();

The file will be complessed anyway with the default method.
I suspect that this bug also affect if you want to use other compression methods if enabled.

Fortunately I have been able to FIX this bug.

The function to modify is:
bool ZipArchive::addFile(const string& entryName, const string& file) const

and here is the change:

    const char* filepath = file.c_str();
    zip_source* source = zip_source_file(zipHandle, filepath, 0, -1);
		if (source != nullptr) {
        libzippp_int64 result = zip_file_add(zipHandle, entryName.c_str(), source, ZIP_FL_OVERWRITE);
        if (result>=0) {
	// HERE STARTS THE FIX
					if (useArchiveCompressionMethod) {
						zip_set_file_compression(zipHandle, result, compressionMethod, 0);
					}
	// END OF THE FIX

I hope you will integrate this fix on the next release so that other users can benefit from this fix.
Thank you.

**Comment by ctabin** [comment]
@Bob590 Hi, thanks for your comment and the fix. It looks right to me.
Would you mind create a PR ?
Thanks ¨

**Comment by Bob590** [comment]
I have made it

**Comment by ctabin** [comment]
Fixed by #163.
