### ISSUE TITLE
unzip progress handling

### ISSUE THREAD

**Issue by Bob590** [ctabin/libzippp#164]
When unzipping there is no support for progress.
Thsi is correct because the code cannot know how much you are unzipping... maybe you unzip only few files from the big archive.
In my application, I have used the same ZipProgressListener object I use for the zip compression.
The problem is that the unzip long operations take place when you unzip the single files.
So the progress could be updated using the file count for example.
My solution:
To update the percent I call list = getEntries() in order to know how many items are in the zip archive.
Then I do a loop to unzip all the files and I update a counter: count;
I count each file unzipped and then I call progression(++count / list.size());
It works for me.

The problem is that when I call the close the percent is zeroed and then after the close I see 100%. This is an odd progression hole.
I have fixed the problem this way:

int ZipArchive::close(void) {
    if (isOpen()) {

        //do not handle zipSource at all because it will be deleted by libzip
        //directly when not necessary anymore

        if(!listeners.empty()) {
            zip_register_progress_callback_with_state(zipHandle, progressPrecision, progress_callback, nullptr, this);
        }
        **if(mode != ReadOnly) // Bob: Fix -> when unzipping reset the progressing made counting the number of file unzipped against the total number of files** 
            progress_callback(zipHandle, 0, this); //enforce the first progression call to be zero

as you can see I have added a test on the mode.
If we have opened the zip file for read only then we are unzipping, while if the mode is write then we are zipping and the initial call (before the close) with percent zero is correct.

If you want to add this very MINOR fix you are welcome.
Thank you.

**Comment by ctabin** [comment]
Hi @Bob590,

Any fix, as minor as it is, is welcomed ;-)
It would be great if you can submit a PR with it.

**Comment by Bob590** [comment]
OK. I have made the pull request.
Enjoy,
Bob

**Comment by ctabin** [comment]
@Bob590 Thanks for the fix !
