### ISSUE TITLE
E0135 class "libzippp::ZipArchive" has no member "fromWriteableBuffer"

### ISSUE THREAD

**Issue by CarlBateman** [ctabin/libzippp#169]
I installed libzippp using vckpkg

I added the following the lines to the start of the file:
```
#include "libzippp/libzippp.h"
using namespace libzippp;
```

The line
`ZipArchive* z1 = ZipArchive::fromWriteableBuffer(&buffer, 4096, ZipArchive::New);`
raises the error 
`E0135	class "libzippp::ZipArchive" has no member "fromWriteableBuffer`

I've checked libzippp.h and fromWriteableBuffer is indeed missing.

**Comment by ctabin** [comment]
Hi @CarlBateman,

This is correct, because the lastet version is not yet released and the version in vcpkg is not up-to-date.
It will be fixed once the version 5.2 will be released.
