### ISSUE TITLE
API for adding batch of files

### ISSUE THREAD

**Issue by ultrablox** [ctabin/libzippp#17]
It would be cool to have something like 
bool ZipArchive::addData
but providing for instance vector of pairs name->data. Because adding 1000 small files one by one is too slow.

**Comment by ctabin** [comment]
Hello,
I implemented the needed methods in #21:
- addFiles
- addEntries
- addSources

Maybe you can have a look and tell me if that is a way that solve your issue.
Thanks !

**Comment by ctabin** [comment]
Note: I guess those new methods won't help you with the performances, because it is just a wrapper around the creation of entries, but there is currently no way to "keep" the input open to add all the data at once in the archive...
