### ISSUE TITLE
Issue opening zip file (constructor or .open() call)

### ISSUE THREAD

**Issue by gizmocuz** [ctabin/libzippp#178]
I am having an issue extracting the attached zip file.
The zip file is created with 'Total Commander'

This one seems go wrong in the constructor already

`ZipArchive zf(sFilename);`

But other zip files return 'false' when calling

`zf.open(ZipArchive::ReadOnly))`

The zip can be extracted with other programs correctly.

[readme.zip](https://github.com/ctabin/libzippp/files/10332520/readme.zip)

For both problems, the error handler is not called

**Comment by gizmocuz** [comment]
Additional note, using zlib/contrib/unzip I am able to open/extract the above zip file

https://github.com/madler/zlib/tree/master/contrib/minizip

**Comment by niclasr** [comment]
Hi, I tried to read your zip file using the following code:
```
#include <iostream>
#include <string>

#include "libzippp.h"

int
main()
{
  std::string sFilename{"readme.zip"};
  libzippp::ZipArchive zf(sFilename);
  if (zf.open(libzippp::ZipArchive::ReadOnly)) {
    std::cout << "zip file opened\n";
    auto entries = zf.getEntries();
    for (auto& entry : entries) {
      std::cout << entry.getName() << "\n";
      std::cout << entry.readAsText() << "\n";
    }
  }
  else {
    std::cout << "zip file could not be opened\n";
  }
  zf.close();

  return 0;
}
```
and it worked without problems for me.

**Comment by gizmocuz** [comment]
@niclasr , thank you very much for testing!

I am now testing on another system and the above works perfectly as well as my original code.

I do have to say that I have just installed libzippp via vcpkg on this machine

Very sorry to bother you! Thanks again!
