### ISSUE TITLE
Minor: when the zip is aborted the percent is modified to 100%

### ISSUE THREAD

**Issue by Bob590** [ctabin/libzippp#179]
Uisng the library I have found this problem.
If you abort the zip operation or the zip quit for an error then you end up with a 100% progress.
It could be acceptable in some applications.
In my case I wish to know at what percentage the zip was stopped.
So i have made a very SMALL change that follows:

int ZipArchive::close(void) {
    if (isOpen()) {

        //do not handle zipSource at all because it will be deleted by libzip
        //directly when not necessary anymore

        if(!listeners.empty()) {
            zip_register_progress_callback_with_state(zipHandle, progressPrecision, progress_callback, nullptr, this);
            zip_register_cancel_callback_with_state(zipHandle, progress_cancel_callback, nullptr, this);
        }
          
        //avoid to reset the progress when unzipping           
        if(mode != ReadOnly) {
          progress_callback(zipHandle, 0, this); //enforce the first progression call to be zero
        }
        
        int result = zip_close(zipHandle);
        zipHandle = nullptr;
        **if(result >= 0)**
          progress_callback(zipHandle, 1, this); //enforce the last progression call to be one

I have added the if(result >= 0) in order to avoid to set 100% percentage in case of errors.
If you think this is good for general use feel free to update the library.
Thank you.

**Comment by Bob590** [comment]
OK. I have done that as suggested.

Thanks,
Bob

**Comment by ctabin** [comment]
Fixed by #180.
