### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64 clang: error: linker command failed with exit code 1 (use -v to see invocation) make: *** [libzippp-shared] Error 1

### ISSUE THREAD

**Issue by ohmerhe** [ctabin/libzippp#19]
when i make project, get this error:
g++ -g -fPIC -c -Ilib/libzip-1.2.0/lib -o obj/libzippp.o -W -Wall -Wextra -ansi -pedantic -std=c++0x src/libzippp.cpp
ar rvs libzippp.a obj/libzippp.o
ar: creating archive libzippp.a
a - obj/libzippp.o
g++ -shared -o libzippp.so obj/libzippp.o
Undefined symbols for architecture x86_64:
  "_zip_close", referenced from:
      libzippp::ZipArchive::close() in libzippp.o
  "_zip_delete", referenced from:
      libzippp::ZipArchive::deleteEntry(libzippp::ZipEntry const&) const in libzippp.o
  "_zip_dir_add", referenced from:
      libzippp::ZipArchive::addEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_discard", referenced from:
      libzippp::ZipArchive::discard() in libzippp.o
  "_zip_fclose", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_file_add", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_file_get_comment", referenced from:
      libzippp::ZipArchive::getEntryComment(libzippp::ZipEntry const&, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_file_rename", referenced from:
      libzippp::ZipArchive::renameEntry(libzippp::ZipEntry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_file_set_comment", referenced from:
      libzippp::ZipArchive::setEntryComment(libzippp::ZipEntry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_fopen_index", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_fread", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_get_archive_comment", referenced from:
      libzippp::ZipArchive::getComment(libzippp::ZipArchive::State) const in libzippp.o
  "_zip_get_num_entries", referenced from:
      libzippp::ZipArchive::getNbEntries(libzippp::ZipArchive::State) const in libzippp.o
  "_zip_name_locate", referenced from:
      libzippp::ZipArchive::hasEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_open", referenced from:
      libzippp::ZipArchive::open(libzippp::ZipArchive::OpenMode, bool) in libzippp.o
  "_zip_set_archive_comment", referenced from:
      libzippp::ZipArchive::setComment(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_set_default_password", referenced from:
      libzippp::ZipArchive::open(libzippp::ZipArchive::OpenMode, bool) in libzippp.o
  "_zip_set_file_compression", referenced from:
      libzippp::ZipArchive::setEntryCompressionEnabled(libzippp::ZipEntry const&, bool) const in libzippp.o
  "_zip_source_buffer", referenced from:
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_source_file", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_source_free", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_stat_index", referenced from:
      libzippp::ZipArchive::getEntries(libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(long, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_stat_init", referenced from:
      libzippp::ZipArchive::getEntries(libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(long, libzippp::ZipArchive::State) const in libzippp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libzippp-shared] Error 1

**Comment by ctabin** [comment]
It seems that you have a problem with the compilation of libzip, not with libzippp. I don't know how you did compile it, however I did never had any problem with it by using `make libraries` and then `make`.

You should look in libzip for further problems.
