### ISSUE TITLE
Memory leak when archive `close` is not successful

### ISSUE THREAD

**Issue by alex-sparus** [ctabin/libzippp#198]
Hello,

Thanks for the wrapper!

There is a bug in `int ZipArchive::close(void) {`

In this section
```
        int result = zip_close(zipHandle);
        zipHandle = nullptr;
        if(result == 0) {
          progress_callback(zipHandle, 1, this); //enforce the last progression call to be one
        }

        if (result!=0) { return result; }
```

The [documentation](https://libzip.org/documentation/zip_close.html) says:
> If successful, archive is freed. Otherwise archive is left unchanged and must still be freed.
> To close and free a zip archive without saving changes, use [zip_discard(3)](https://libzip.org/documentation/zip_discard.html).

Additionally, libzippp currently does not provide a way to get the error describing what went wrong.

Cheers,
Alex

**Comment by ctabin** [comment]
Hi @alex-sparus,

Thanks for the message. Actually, you can retrieve the error code from `ZipArchive::close`, which is described in the snippet you just give. BTW it is the libzip error code.

But it seems you're correct about the inconsistent behavior, the `zipHandle` shouldn't be reset to `nullptr` if the result is not zero :thinking:
