### ISSUE TITLE
The install of libzippp.pc is not working

### ISSUE THREAD

**Issue by niclasr** [ctabin/libzippp#215]
When setting LIBZIPPP_GNUINSTALLDIRS and BUILD_SHARED_LIBS to ON the below happens in the install step:
CMake Error at cmake_install.cmake:98 (file):
  file INSTALL cannot find "/generated/libzipp.pc": No such file or
  directory.

The pull request #214 fixes this.

**Comment by ctabin** [comment]
Fixed by #214.
