### ISSUE TITLE
Archive with encryption causes zip_fopen_index() to fail 

### ISSUE THREAD

**Issue by andrelehto** [ctabin/libzippp#227]
When trying to decompress an archive with encryption (encrypted using 7z, `ZipCrypto` or `AES-256` does not matter), trying to read data from entries always returns `LIBZIPPP_ERROR_FOPEN_FAILURE`, i.e `zip_fopen_index()` has failed. This only occurs on archives with encryption.

Small code snippet:
```c++
int main(int argc, char** argv) {
   std::string destination = "C:\\temp\\temporary\\";
   std::string source = "C:\\temp\\test.zip";

   libzippp::ZipArchive archive(source, "test");

   bool open = archive.open(libzippp::ZipArchive::ReadOnly);
   std::vector<libzippp::ZipEntry> entries = archive.getEntries();
   std::vector<libzippp::ZipEntry>::iterator it;
   libzippp::ZipEntry entry;

   std::string folder;
   std::string target;
   for (it = entries.begin(); it != entries.end(); ++it)
   {
      entry = *it;
      if (entry.isFile())
      {
         folder = destination.data() + std::filesystem::path(entry.getName()).parent_path().string();
         target = folder + "\\" + std::filesystem::path(entry.getName()).filename().string();

         /* Create directory if it does not exist */
         if (!std::filesystem::exists(folder))
            std::filesystem::create_directories(folder);

         std::ofstream stream(target, std::ios::out | std::ios::binary);
         int returnCode = entry.readContent(stream);
         stream.close();
      }
   }
   archive.close();
   return 0;
}
```

returnCode will be set to `LIBZIPPP_ERROR_FOPEN_FAILURE`  for each entry (**only**) if the archive is encrypted.

The strings `destination`, `source` as well as the password passed to the `ZipArchive` are set up for my example and will have to be adjusted.

**Comment by andrelehto** [comment]
The issue was the the preprocessor flag LIBZIPPP_WITH_ENCRYPTION was not set properly. Since I installed `libzippp` using vcpkg, the preprocessor flag was not being used inside the loaded library.

**Comment by ctabin** [comment]
Hi @andrelehto,
Thanks for the feedback. I'll see to add a check in order to display a message when the flag is not set.

**Comment by andrelehto** [comment]
Hi @ctabin, it would perhaps be a good feature for the future to be able to set the state of the LIBZIPPP_WITH_ENCRYPTION flag while installing libzippp with vcpkg.
