### ISSUE TITLE
How to extract to a directory

### ISSUE THREAD

**Issue by Lecrapouille** [ctabin/libzippp#23]
Not an issue ! I would like to use your API but I did not see the method for extracting all files and subdirectories from an archive into a desired directory. In the same way, how to zip a whole directory with all these files and subdirectories ? Have I to myself iterate recursively for each files for each directory and add or read files ? Sound weird I just want to zip and unzip a directory but not working directly in the archive ! How to do that easily ?

**Comment by embeddedmz** [comment]
Hello,

You can take inspiration from the "ExtractAllFilesFromZip" method of my "c++ helpers" project that uses libzippp : "https://github.com/embeddedmz/helpers-cpp/blob/master/HELPERS/Helpers.cpp"

Take a look to the other methods, they might help you.

Best regards.

**Comment by ctabin** [comment]
Hello,

@Lecrapouille you're right, there is no helper directly in libzippp to extract/zip a directory, you'll have to do it yourself. Maybe it's a feature I will implement in future releases, but I don't want to have a dependency on `boost` like the helpers shown by @embeddedmz :-)

The API to zip a directory is straightforward, but you have to itererate on the directory yourself.

**Comment by Lecrapouille** [comment]
Hi @embeddedmz and @ctabin yes that is what I was looking for :) Thanks a lot. You should add a link to this helper on your README (I think I'll not the one needing it).
