### ISSUE TITLE
Cannot link to static libraries 

### ISSUE THREAD

**Issue by jakobloeg** [ctabin/libzippp#27]
Hello, I have tried to use your project to link directly to functions provided by libzip. In my CMakeLists.txt file I include libraries  "libzippp_static.lib", "zipstatic.lib" and "zlibstaticd.lib". I have also included the necessary include directories with header files. When I try to build the project I get errors in this form:

: error LNK2019: unresolved external symbol __imp_zip_add referenced in function  ...

Can you help me solve this error?

**Comment by ctabin** [comment]
Hello,

I came across the same problem while trying to link libzip (not libzippp) statically and I haven't figure out what was the problème (ie missing a #define, version of CMake, ...).

**Comment by ctabin** [comment]
Seems to be related to #34, hence I close this issue.
