### ISSUE TITLE
Unable to compile with VC2015 using libzippp-v2.1-1.5.1-windows-ready_to_compile.zip

### ISSUE THREAD

**Issue by sinall** [ctabin/libzippp#34]
I changed compile.bat:
`SET vs2012devprompt=C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat
`

> Compiling libzip...
> CMake Error at CMakeLists.txt:8 (PROJECT):
>   Failed to run MSBuild command:
> 
>     C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe
> 
>   to get the value of VCTargetsPath:
> 
>     Microsoft (R) Build Engine version 4.7.2558.0
>     [Microsoft .NET Framework, version 4.0.30319.42000]
>     Copyright (C) Microsoft Corporation. All rights reserved.
> 
>     Build started 2018-06-08 3:22:10 PM.
>     Project "D:\Documents\Visual_Studio_2015\Projects\MyProject\packages\libzippp-v2.1-1.5.1\lib\libzip-1.5.1\build\CMakeFiles\3.11.3\VCTargetsPath.vcxproj" on node 1 (default targets).
>     D:\Documents\Visual_Studio_2015\Projects\MyProject\packages\libzippp-v2.1-1.5.1\lib\libzip-1.5.1\build\CMakeFiles\3.11.3\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
>     Done Building Project "D:\Documents\Visual_Studio_2015\Projects\MyProject\packages\libzippp-v2.1-1.5.1\lib\libzip-1.5.1\build\CMakeFiles\3.11.3\VCTargetsPath.vcxproj" (default targets) -- FAILED.
> 
>     Build FAILED.
> 
>     "D:\Documents\Visual_Studio_2015\Projects\MyProject\packages\libzippp-v2.1-1.5.1\lib\libzip-1.5.1\build\CMakeFiles\3.11.3\VCTargetsPath.vcxproj" (default target) (1) ->
>       D:\Documents\Visual_Studio_2015\Projects\MyProject\packages\libzippp-v2.1-1.5.1\lib\libzip-1.5.1\build\CMakeFiles\3.11.3\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
> 
>         0 Warning(s)
>         1 Error(s)
> 
>     Time Elapsed 00:00:01.14
> 
> 
>   Exit code: 1
> 
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "D:/Documents/Visual_Studio_2015/Projects/MyProject/packages/libzippp-v2.1-1.5.1/lib/libzip-1.5.1/build/CMakeFiles/CMakeOutput.log".
> [ERROR] Unable to compile libzip
> Microsoft Windows [Version 10.0.14393]
> (c) 2016 Microsoft Corporation. All rights reserved.

**Comment by sinall** [comment]
[Another suggestion]: the binaries package could include header files.

**Comment by ctabin** [comment]
Hello,

Thanks for the report. 
Can you provide the "CMakeOutput.log" ?

Best,

**Comment by sinall** [comment]
It lost the output file.
From the above error message is:

> error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found.

**Comment by hsdk123** [comment]
Hi, I'm getting the exact same error. (using visual studio 2019)

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.0.0
** Copyright (c) 2019 Microsoft Corporation
**********************************************************************
Compiling lizippp...
CMake Error at CMakeLists.txt:4 (PROJECT):
  Failed to run MSBuild command:

    C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

  to get the value of VCTargetsPath:

    Microsoft (R) Build Engine version 4.7.3062.0
    [Microsoft .NET Framework, version 4.0.30319.42000]
    Copyright (C) Microsoft Corporation. All rights reserved.

    Build started 16/04/2019 Tue 08:58:30.
    Project "C:\Users\hsdk.bd\Desktop\libzippp-v2.1-1.5.1\build\CMakeFiles\3.13.19031502-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
    C:\Users\hsdk.bd\Desktop\libzippp-v2.1-1.5.1\build\CMakeFiles\3.13.19031502-MSVC_2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    Done Building Project "C:\Users\hsdk.bd\Desktop\libzippp-v2.1-1.5.1\build\CMakeFiles\3.13.19031502-MSVC_2\VCTargetsPath.vcxproj" (default targets) -- FAILED.

    Build FAILED.

    "C:\Users\hsdk.bd\Desktop\libzippp-v2.1-1.5.1\build\CMakeFiles\3.13.19031502-MSVC_2\VCTargetsPath.vcxproj" (default target) (1) ->
      C:\Users\hsdk.bd\Desktop\libzippp-v2.1-1.5.1\build\CMakeFiles\3.13.19031502-MSVC_2\VCTargetsPath.vcxproj(14,2): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

        0 Warning(s)
        1 Error(s)

    Time Elapsed 00:00:00.20


  Exit code: 1



-- Configuring incomplete, errors occurred!
See also "C:/Users/hsdk.bd/Desktop/libzippp-v2.1-1.5.1/build/CMakeFiles/CMakeOutput.log".
[ERROR] Unable to compile libzippp
Microsoft Windows [Version 10.0.16299.125]
(c) 2017 Microsoft Corporation. All rights reserved.
```

**Comment by hsdk123** [comment]
"C:/Users/hsdk.bd/Desktop/libzippp-v2.1-1.5.1/build/CMakeFiles/CMakeOutput.log" contents:

```
The system is: Windows - 10.0.16299 - AMD64
```

**Comment by hsdk123** [comment]
I feel it might just be more easier if you could provide a visual studio solution file. Then the user can just update that solution file to their Visual Studio on their end.

**Comment by Flamefire** [comment]
Better solution: Both zlib and libzip provide a `CMakeLists` so in libzippps CMakeLists you can do something along the lines of:

```
find_package(LIBZIP)
if(NOT LIBZIP_FOUND)
  set(contrib_zlib_dir ${CMAKE_CURRENT_SOURCE_DIR}/lib/zlib)
  set(contrib_libzip_dir ${CMAKE_CURRENT_SOURCE_DIR}/lib/libzip)
  if(EXISTS ${contrib_zlib_dir} AND EXISTS ${contrib_libzip_dir})
    execute_process(
      COMMAND ${CMAKE_COMMAND} -G${CMAKE_GENERATOR} -A${CMAKE_GENERATOR_PLATFORM} -T${CMAKE_GENERATOR_TOOLSET} . -DCMAKE_INSTALL_PREFIX=<something reasonable then added to CMAKE_PREFIX_PATH>
      WORKING_DIRECTORY "${contrib_zlib_dir}"
    )
    execute_process(
        COMMAND ${CMAKE_COMMAND} --build . --target install
        RESULT_VARIABLE result
        WORKING_DIRECTORY "${contrib_zlib_dir}"
    )
    add_subdirectory(${contrib_libzip_dir})
endif()
```

Or use `FetchContent` from Cmake 3.11 for the execute_process stuff.

Alternatively update the https://github.com/ctabin/libzippp/blob/master/compile.bat to at least remove all `-G"Visual Studio 11"` and the `vs2012devprompt` line and usage and tell users to open a VS dev prompt to run the script.

**Comment by ctabin** [comment]
Also, the vcpkg port should bring an easy solution.
