### ISSUE TITLE
libzippp::ZipArchive seems to be just support utf8 ....

### ISSUE THREAD

**Issue by aijyo** [ctabin/libzippp#37]
Just as the title, when use libzippp to commpress some file with  Chinese in path(not just ANSI) failed,  through the source code i find it seems to be just support utf8....
So,  I think it can wrap a transcode to support  tstring... not utf8
![image](https://user-images.githubusercontent.com/7956449/48322600-5c549d00-e663-11e8-9c6e-3a83657f3230.png)

**Comment by Flamefire** [comment]
This would rather be an issue of the underlying https://github.com/nih-at/libzip

However the better solution: [UTF8 Everywhere](http://utf8everywhere.org/), so just convert input strings to UTF8 at the interface and use it exclusively in all strings.

**Comment by ctabin** [comment]
I'll close this issue, as it is related to #53 and the PR #63 should bring some improvements about it.
