### ISSUE TITLE
"make" command as per the README is failing

### ISSUE THREAD

**Issue by Arjunkalidas** [ctabin/libzippp#47]
I am getting this error, when I perform a 'make'. But the step 2 - 'make libraries' is working perfectly fine.

Any suggestions? What is with the architecture error? Isn't this supported for x86_64 arch?

`202 warnings generated.
ar rvs libzippp.a obj/libzippp.o
r - obj/libzippp.o
c++ -shared -o libzippp.so obj/libzippp.o
Undefined symbols for architecture x86_64:
  "_zip_close", referenced from:
      libzippp::ZipArchive::close() in libzippp.o
  "_zip_delete", referenced from:
      libzippp::ZipArchive::deleteEntry(libzippp::ZipEntry const&) const in libzippp.o
  "_zip_dir_add", referenced from:
      libzippp::ZipArchive::addEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_discard", referenced from:
      libzippp::ZipArchive::discard() in libzippp.o
  "_zip_fclose", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_file_add", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_file_get_comment", referenced from:
      libzippp::ZipArchive::getEntryComment(libzippp::ZipEntry const&, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_file_rename", referenced from:
      libzippp::ZipArchive::renameEntry(libzippp::ZipEntry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_file_set_comment", referenced from:
      libzippp::ZipArchive::setEntryComment(libzippp::ZipEntry const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_fopen_index", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_fread", referenced from:
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, bool, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
      libzippp::ZipArchive::readEntry(libzippp::ZipEntry const&, std::__1::basic_ofstream<char, std::__1::char_traits<char> >&, libzippp::ZipArchive::State, unsigned long) const in libzippp.o
  "_zip_get_archive_comment", referenced from:
      libzippp::ZipArchive::getComment(libzippp::ZipArchive::State) const in libzippp.o
  "_zip_get_num_entries", referenced from:
      libzippp::ZipArchive::getNbEntries(libzippp::ZipArchive::State) const in libzippp.o
  "_zip_name_locate", referenced from:
      libzippp::ZipArchive::hasEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, bool, bool, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_open", referenced from:
      libzippp::ZipArchive::open(libzippp::ZipArchive::OpenMode, bool) in libzippp.o
  "_zip_set_archive_comment", referenced from:
      libzippp::ZipArchive::setComment(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_set_default_password", referenced from:
      libzippp::ZipArchive::open(libzippp::ZipArchive::OpenMode, bool) in libzippp.o
  "_zip_set_file_compression", referenced from:
      libzippp::ZipArchive::setEntryCompressionEnabled(libzippp::ZipEntry const&, bool) const in libzippp.o
  "_zip_source_buffer", referenced from:
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_source_file", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
  "_zip_source_free", referenced from:
      libzippp::ZipArchive::addFile(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) const in libzippp.o
      libzippp::ZipArchive::addData(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, void const*, unsigned long, bool) const in libzippp.o
  "_zip_stat_index", referenced from:
      libzippp::ZipArchive::getEntries(libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(long, libzippp::ZipArchive::State) const in libzippp.o
  "_zip_stat_init", referenced from:
      libzippp::ZipArchive::getEntries(libzippp::ZipArchive::State) const in libzippp.o
      libzippp::ZipArchive::getEntry(long, libzippp::ZipArchive::State) const in libzippp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libzippp-shared] Error 1`

**Comment by Flamefire** [comment]
Are you compiling on OSX? It seems libzip (the dependency) was not compiled for all archs. Try using it's cmake build manually or add (somehow) the relevant `-arch` parameter to its compilation flags.

**Comment by ctabin** [comment]
Since there was not response here and as there is now the CMake and the vcpkg port, I close this issue.
