### ISSUE TITLE
ZipEntry getName return incorrect

### ISSUE THREAD

**Issue by HoangBaoThien** [ctabin/libzippp#53]
ZipArchive::getEntries with state =ORIGINAL return modified name (convert it to UTF-8)
![image](https://user-images.githubusercontent.com/20065944/73874535-43e32a80-4886-11ea-876e-36573264e7fa.png)
![image](https://user-images.githubusercontent.com/20065944/73874548-4c3b6580-4886-11ea-8c53-ea81e59f6266.png)

When use ZipArchive::getEntries
![image](https://user-images.githubusercontent.com/20065944/73876183-26fc2680-4889-11ea-8f20-8f278e3add4e.png)

When use libzip (https://libzip.org/)

![image](https://user-images.githubusercontent.com/20065944/73876210-31b6bb80-4889-11ea-8d2a-6b0705b998d8.png)

My zip file
[test1.zip](https://github.com/ctabin/libzippp/files/4161581/test1.zip)

Windows default ASCII CodePage 932- ANSI/OEM Japanese; Japanese (Shift-JIS)

References:
https://docs.microsoft.com/vi-vn/windows/win32/intl/code-page-identifiers
https://docs.microsoft.com/vi-vn/windows/win32/api/winnls/nf-winnls-getacp?redirectedfrom=MSDN
#References:https://github.com/ctabin/libzippp/issues/37

**Comment by ctabin** [comment]
Hi @HoangBaoThien,

Thanks for the issue and sorry to reply so late.
Since I won't be able to look at it soon, would it be possible for you to submit a PR ? :pray: 

Thanks !
