### ISSUE TITLE
Whether to support Chinese name file?

### ISSUE THREAD

**Issue by IYinxf** [ctabin/libzippp#67]
I'll use libzippp for Windows and Linux,can I use it to open the Chinese name file?

**Comment by ctabin** [comment]
Hi @IYinxf,

I did not test directly Chinese input, but I would say that if you use UTF-8 everywhere, that shouldn't be an issue. You can check #37 for more details.

Feel free to reopen this issue if you have some trouble with the encoding.

Best,
Cédric
