### ISSUE TITLE
setEntryCompressionEnabled not return right value

### ISSUE THREAD

**Issue by Xrysnow** [ctabin/libzippp#69]
`zip_set_file_compression` returns 0 when success and -1 when failed, so it's missing `==0` here.
https://github.com/ctabin/libzippp/blob/da80707811d2ec886f44b3e3e53a74a415e13ea4/src/libzippp.cpp#L252

**Comment by ctabin** [comment]
@Xrysnow thanks for the issue, that's fixed !
