### ISSUE TITLE
Use a write function for readEntry?

### ISSUE THREAD

**Issue by Xrysnow** [ctabin/libzippp#71]
I want to read an entry to my custom buffer, but I find it's not easy to use it in `readEntry`. Would you like to add a new version that accepts `std::function<bool(const char*,libzippp_uint64)>`?
Just replace `ofOutput.write(data, size); if (!ofOutput) {...}` with `if (!writeFunc(data, size)) {...}` and the `std::ostream` version can use
```cpp
[=](const char* data,libzippp_uint64 size){ ofOutput.write(data, size); return bool(ofOutput); }
```

**Comment by ctabin** [comment]
Hi @Xrysnow 
You're suggestion seems interesting. Do you mind posting a PR ? Thanks !
