### ISSUE TITLE
Possible to create a ZipArchive in memory, and add it as a file to another archive?

### ISSUE THREAD

**Issue by fridgerator** [ctabin/libzippp#79]
I have a requirement to create one archive, with more archives contained within.

For the archives contained within I can create new files and then add them to the main archive, this works.  However if would be more efficient if I could create them in memory and add them to the main archive.

**Comment by fridgerator** [comment]
Reading through the libzippp source and libzip documentation, doesn't seem like it would be possible.

**Comment by ctabin** [comment]
Hi @fridgerator,
Unfortunately you're right. For now it is not possible to generate a in-memory zip through libzippp.
This seems to be possible by using `zip_open_from_source` directly from lizbip, but there is no function wrapper in libzippp for now.

**Comment by ctabin** [comment]
In the next version, it is possible to create in-memory zip archives (cf example in the README).
