### ISSUE TITLE
Unable to use libzip pkgcfg to find include and lib directories and unsuccessful install using vcpkg

### ISSUE THREAD

**Issue by apolo49** [ctabin/libzippp#93]
I am attempting to use CMake GUI to compile libzippp static to statically link to libzip and zlib both of which seem to be working smoothly and have downloaded successfully using vcpkg. Attempting to compile using the version distributed vcpkg (libzippp:x86-windows-static) leads to these compilation errors:

```
ExtractZip.obj : error LNK2019: unresolved external symbol "public: long __thiscall libzippp::ZipArchive::getNbEntries(enum libzippp::ZipArchive::State)const " (?getNbEntries@ZipArchive@libzippp@@QBEJW4State@12@@Z) referenced
```

and 

```
ExtractZip.obj : error LNK2019: unresolved external symbol "public: int __thiscall libzippp::ZipEntry::readContent(class std::basic_ostream<char,struct std::char_traits<char> > &,enum libzippp::ZipArchive::State,unsigned long)const " (?readContent@ZipEntry@libzippp@@QBEHAAV?$basic_ostream@DU?$char_traits@D@std@@@std@@W4State@ZipArchive@2@K@Z) referenced
```

So as a result of this I decided to try and link to the already compiled libzip and compile libzippp manually using CMake and VS2019, however I cannot generate the solution as I get this error when trying to use the libzip pkgcfg which I believe is located at `lib/pkgconfig/zip.pc` and I get this error:

```
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find LIBZIP (missing: LIBZIP_LIBRARY LIBZIP_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindLIBZIP.cmake:17 (find_package_handle_standard_args)
  CMakeLists.txt:20 (find_package)
```

I'm trying to build for Win32, x86, using CMake 3.18.0 and VS2019.

Thank you for any help.

**Comment by ctabin** [comment]
Hi @apolo49,
Could you please provide a minimal configuration of what you use in order to reproduce the problem ?
Thanks.

**Comment by ctabin** [comment]
Without any further information, I'll close this issue.
