### ISSUE TITLE
i have to call zf.close() to flush to disk?

### ISSUE THREAD

**Issue by dotkt** [ctabin/libzippp#94]
i call zf.addFile gets true,but the zip file did not show up.
so i call zf.addfile and zf.close(),then the zip file shows up.
is this the right usage?

**Comment by ctabin** [comment]
Hi @dotkt,

I hereby confirm that you have to call `close()` to flush to the disk.
This behavior is based on the underlying [zip_close()](https://libzip.org/documentation/zip_close.html) function.

**Comment by dotkt** [comment]
ok many thanks
